version: '3.9'

services:
  serverinstance:
    image: homeguard-server
    restart: always
    expose: 
      - "5000"
    deploy:
      replicas: 5

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - serverinstance
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
    name: serverinstance
